"""Generate small flash tables from the exact training frontend contract."""
from pathlib import Path
import sys
import numpy as np

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))
from hybrid.frontend import _HANN, _MEL, FRONTEND_VERSION


def values(name, ctype, data):
    text = []
    for value in data:
        text.append(f"{float(value):.9e}f" if ctype == "float" else str(int(value)))
    rows = [", ".join(text[i:i + 8]) for i in range(0, len(text), 8)]
    return f"static const {ctype} {name}[] = {{\n  " + ",\n  ".join(rows) + "\n};\n"


def main():
    starts, offsets, weights = [], [0], []
    for mel in range(64):
        bins = (_MEL[:, mel] > 0).nonzero()[0]
        starts.append(int(bins[0]))
        weights.extend(_MEL[bins, mel])
        offsets.append(len(weights))
    output = "#pragma once\n// Generated by tools/generate_frontend_tables.py; do not hand-edit.\n"
    output += f"// Contract: {FRONTEND_VERSION}\nnamespace clap_frontend_tables {{\n"
    output += values("hann", "float", _HANN)
    angles = -2 * np.pi * np.arange(256) / 512
    output += values("fftReal", "float", np.cos(angles).astype(np.float32))
    output += values("fftImag", "float", np.sin(angles).astype(np.float32))
    output += values("melStart", "uint16_t", starts)
    output += values("melOffset", "uint16_t", offsets)
    output += values("melWeight", "float", weights)
    output += "}\n"
    target = Path(__file__).resolve().parents[1] / "clap_double" / "clap_frontend_tables.h"
    target.write_text(output, encoding="utf-8")
    print(f"Wrote {target.name}: {len(weights)} sparse mel weights")


if __name__ == "__main__":
    main()
